apiVersion: 1

datasources:
  - name: InfluxDB-Customer
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: iss-iot
      defaultBucket: customer_1
      tlsSkipVerify: true
    secureJsonData:
      token: my-super-secret-auth-token-change-me
    isDefault: true
    editable: true
